AWSTemplateFormatVersion: 2010-09-09
Description: >
  MSP T2 Docker Basics
  Amazon AWS Cloud9 Environment EC2
Resources:
  Cloud9IDE:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      #Name environment
      Name: Docker Basics
      Description: Amazon AWS Cloud9 Environment EC2 for Docker Basics
      #Configure settings
      ConnectionType: CONNECT_SSH
      InstanceType: t2.micro
      ImageId: ubuntu-18.04-x86_64
      AutomaticStopTimeMinutes: 30
      #OwnerArn: String
      #Repositories: 
      #  - Repository
      #SubnetId: String
      #Tags: 
      #  - Tag
Outputs:
  Cloud9URL:
    Description: Cloud9 Environment
    Value:
      Fn::Join:
      - ''
      - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
        - !Ref 'Cloud9IDE'